services:
  - type: worker
    name: midknight-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: PREFIX
        value: .
      - key: BOT_MODE
        value: public
